// wasm-loader — lazily initialize the concurrent-psbt-wasm module and expose
// its op exports as the shared-frontend `PtjWasmModule` glue surface.
//
// The wasm-bindgen `--target web` glue (pkg/concurrent_psbt_wasm.js) exports a
// default init() that fetches + instantiates the .wasm, plus one named export
// per #[wasm_bindgen(js_name = ...)] function — camelCase (inspect, create,
// join, sort, makeUnordered, atomize, concatenate, exportBip174, importBip174,
// pay, confirm, payments, localSync, initPanicHook, version). That surface IS
// `PtjWasmModule` (shared-frontend/backends/wasm.ts); no adaptation layer.

// TARGET (integrated): import from the shared frontend package/path.
import type { PtjWasmModule } from "../shared-frontend/backends/wasm.js";

// CPSBT_WASM_URL is a build-time define (feature-flags.md); default is
// same-origin, SW-cached. Kept as a constant so the bundler can inline it.
const CPSBT_WASM_URL = "./pkg/concurrent_psbt_wasm_bg.wasm";

// The wasm-bindgen `--target web` ESM glue. Generated by the PWA build
// (wasm-bindgen/build-wasm.sh -> pkg/); not present in this scratch skeleton —
// the specifier is a const (not an import literal) so type-checking does not
// require the generated file to exist.
const CPSBT_GLUE_MODULE = "../../pkg/concurrent_psbt_wasm.js";

interface WasmGlue {
  // default init(url): fetch + instantiate; getRandomValues resolved by glue.
  default(url: string): Promise<unknown>;
  initPanicHook(): void;
}

/**
 * Initialize the wasm module once and return its op surface. The caller caches
 * the returned promise so this runs at most once per page.
 */
export async function loadWasm(debug = false): Promise<PtjWasmModule> {
  const glue = (await import(/* @vite-ignore */ CPSBT_GLUE_MODULE)) as WasmGlue;
  await glue.default(CPSBT_WASM_URL);
  if (debug) glue.initPanicHook();
  // The named exports are the camelCase js_name functions; narrow to the
  // shared glue-surface type.
  return glue as unknown as PtjWasmModule;
}
