name: CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Compute fetch depth
        id: fetch-depth
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "depth=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "$GITHUB_OUTPUT"
          else
            echo "depth=0" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
        with:
          fetch-depth: ${{ steps.fetch-depth.outputs.depth }}
      - uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41 # main
      - uses: DeterminateSystems/magic-nix-cache-action@55718cd9ebf1737a061487d5ada21abf31e99a98 # main
      - name: Validate commits
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            NIX_FLAKE_SHALLOW=1 nix run '.?shallow=1#validate-commits' -- --git --forward --parallel --keep-going --print-build-logs \
              -- '${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.merge_commit_sha }}'
          else
            NIX_FLAKE_SHALLOW=1 nix run '.?shallow=1#validate-commits' -- --git --forward --parallel --keep-going --print-build-logs
          fi
