name: Nextest (Darwin)
on:
  push:
    branches: [main]
  pull_request:
permissions:
  contents: read
jobs:
  nextest:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41 # main
      - uses: DeterminateSystems/magic-nix-cache-action@55718cd9ebf1737a061487d5ada21abf31e99a98 # main
      - name: Run nextest
        run: nix build --no-update-lock-file --out-link result-nextest '.#checks.aarch64-darwin.tests-nightly-dev'
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: nextest-nightly-dev-aarch64-darwin
          path: result-nextest/nextest-run.zip
